variables:
    CI_IMAGE_TAG: "opengl"
    MODERNGL_DEBUGGING: "true"
    JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"

job:
    image: "juliagpu/julia:v1.0-${CI_IMAGE_TAG}"
    before_script:
        - apt-get -qq update
        # glfw
        - apt-get install -y cmake libxrandr-dev libxinerama-dev libxcursor-dev mesa-utils
        # cairo etc
        - apt-get install -y gettext libpango1.0-0 libcairo2 libmagickwand-6.q16
        - apt-get install -y ffmpeg

    script:
      - julia -e 'using InteractiveUtils; versioninfo()'
      - julia -e 'using Pkg; Pkg.build("GLMakie"); Pkg.test("GLMakie")'
